document.getElementById("container").style.backgroundColor = "lightgrey";
document.getElementById("header-container").style.backgroundColor = "green";
document.querySelector(".emergency-tasks").style.backgroundColor = "lightsalmon";
document.querySelectorAll(".emergency-tasks h3")[0].style.backgroundColor = "violet";
document.querySelectorAll(".emergency-tasks h3")[1].style.backgroundColor = "violet";
document.querySelector(".no-emergency-tasks").style.backgroundColor = "yellow";
document.querySelectorAll(".no-emergency-tasks h3")[0].style.backgroundColor = "black";
document.querySelectorAll(".no-emergency-tasks h3")[1].style.backgroundColor = "black";
document.querySelector("#footer-container").style.backgroundColor = "darkgreen";